# Customer Churn Prediction - Data Inspection
## Objective

Before building a machine learning model, it is important to understand the data we are working with.

In this notebook, I will inspect the Telco Customer Churn dataset to understand its structure, data types, data quality, target distribution, and the meaning of different features.

The main goals of this inspection are to:

- Understand what each column represents
- Identify numerical and categorical features
- Check for missing and duplicate values
- Find columns with incorrect or unexpected data types
- Understand the distribution of the target variable
- Identify irrelevant features and potential data leakage
- Detect any data-quality issues that need to be addressed before preprocessing

The findings from this notebook will be used to make informed decisions during the preprocessing and modeling stages.

## 1. Import Libraries

In [2]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## 2. Load the Dataset

In [3]:
df = pd.read_excel("../data/raw/Telco_customer_churn.xlsx")
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

## 3. Basic Dataset Overview

In [4]:
# Sample 
df.sample(5)

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2764,0013-MHZWF,1,United States,California,Midpines,95345,"37.581496, -119.972762",37.581496,-119.972762,Female,...,Month-to-month,Yes,Credit card (automatic),69.4,571.45,No,0,55,5108,NaN
5689,0128-MKWSG,1,United States,California,Stevenson Ranch,91381,"34.364153, -118.615583",34.364153,-118.615583,Female,...,Month-to-month,No,Mailed check,45.8,1147,No,0,45,3287,NaN
3909,8929-KSWIH,1,United States,California,San Jose,95111,"37.284265, -121.827673",37.284265,-121.827673,Male,...,Two year,No,Bank transfer (automatic),99.3,2513.5,No,0,23,3847,NaN
5723,6854-EXGSF,1,United States,California,Mt Baldy,91759,"34.231318, -117.662032",34.231318,-117.662032,Female,...,Month-to-month,Yes,Bank transfer (automatic),65.5,573.15,No,0,38,3033,NaN
3807,8766-PAFNE,1,United States,California,Hayward,94545,"37.62984, -122.120843",37.629840,-122.120843,Male,...,Two year,Yes,Credit card (automatic),79.1,5564.85,No,0,29,5872,NaN

In [5]:
# Checking number of rows and columns
print(f"""Total No of Rows : {df.shape[0]}
Total No of Columns : {df.shape[1]}
""")

Total No of Rows : 7043
Total No of Columns : 33

### Column Names

In [6]:
for index , colName in enumerate(df.columns):
    print(f"{index+1}.{colName}")

1.CustomerID
2.Count
3.Country
4.State
5.City
6.Zip Code
7.Lat Long
8.Latitude
9.Longitude
10.Gender
11.Senior Citizen
12.Partner
13.Dependents
14.Tenure Months
15.Phone Service
16.Multiple Lines
17.Internet Service
18.Online Security
19.Online Backup
20.Device Protection
21.Tech Support
22.Streaming TV
23.Streaming Movies
24.Contract
25.Paperless Billing
26.Payment Method
27.Monthly Charges
28.Total Charges
29.Churn Label
30.Churn Value
31.Churn Score
32.CLTV
33.Churn Reason

## 4. Understanding the Target Variable

The target variable represents whether a customer has churned.

In this dataset, churn is represented using both a label (`Churn Label`) and a numerical value (`Churn Value`). I will examine the available representations and their distribution before deciding which one to use for modeling.

In [7]:
# Target column 
target_column = df["Churn Value"]
print("Target Column :", target_column.name)
print(f'''Five sample Values
{target_column.sample(5).to_list()}
''')

Target Column : Churn Value
Five sample Values
[0, 1, 0, 0, 0]

## 5. Data Types and Feature Types

Understanding the data types is important because different types of features require different preprocessing techniques.

I will inspect the dataset's data types and separate numerical and categorical features.

In [8]:
# Dataset info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 2.9+ MB

## 6. Missing Values

Missing values can affect both data analysis and model training. I will check for missing values and also look for values that may represent missing data without being stored as actual `NaN` values.

In [9]:
df.isnull().sum()

CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

## 7. Duplicate Records and Unique Identifiers

Duplicate records can affect our analysis and model training. I will also check whether `CustomerID` uniquely identifies each customer.

In [10]:
# Checking for duplicated rows
df.duplicated().sum()

np.int64(0)

In [11]:
# Checking if Customer ID is unique
unique_ids= df["CustomerID"].nunique()
print(unique_ids == len(df))

True

## 8. Categorical Feature Inspection

Categorical features can contain different categories, unexpected values, or inconsistent representations. I will inspect their unique values to understand what each feature actually contains.

In [12]:
# Categorical columns
categorical_cols = df.select_dtypes(include = ['object' ,'category'])

In [13]:
# Checking unique values of categorical columns
for col in categorical_cols.columns:
    print(f"\n{col}")
    print(df[col].unique())

CustomerID
<ArrowStringArray>
['3668-QPYBK', '9237-HQITU', '9305-CDSKC', '7892-POOKP', '0280-XJGEX',
 '4190-MFLUW', '8779-QRDMV', '1066-JKSGK', '6467-CHFZW', '8665-UTDHZ',
 ...
 '0871-OPBXW', '3605-JISKB', '9767-FFLEM', '8456-QDAVC', '7750-EYXWZ',
 '2569-WGERO', '6840-RESVB', '2234-XADUH', '4801-JZAZL', '3186-AJIEK']
Length: 7043, dtype: str

Country
<ArrowStringArray>
['United States']
Length: 1, dtype: str

State
<ArrowStringArray>
['California']
Length: 1, dtype: str

City
<ArrowStringArray>
[    'Los Angeles',   'Beverly Hills', 'Huntington Park',         'Lynwood',
  'Marina Del Rey',       'Inglewood',    'Santa Monica',        'Torrance',
        'Whittier',        'La Habra',
 ...
      'Janesville',      'Litchfield',        'Loyalton',        'Madeline',
    'Markleeville',         'Milford',         'Calpine',        'Standish',
        'Tulelake',  'Olympic Valley']
Length: 1129, dtype: str

Lat Long
<ArrowStringArray>
['33.964131, -118.272783',  '34.059281, -118.30742', '34.048013, -118.293953',
 '34.062125, -118.315709', '34.039224, -118.266293', '34.066367, -118.309868',
  '34.02381, -118.156582', '34.066303, -118.435479', '34.099869, -118.326843',
 '34.089953, -118.294824',
 ...
 '40.294034, -120.512622', '40.507272, -120.338228', '39.637471, -120.226338',
 '41.042003, -120.506086',  '38.735789, -119.85798', '40.181279, -120.392967',
 '39.672813, -120.456699', '40.346634, -120.386422', '41.813521, -121.492666',
 '39.191797, -120.212401']
Length: 1652, dtype: str

Gender
<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

Senior Citizen
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Partner
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Dependents
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Phone Service
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Multiple Lines
<ArrowStringArray>
['No', 'Yes', 'No phone service']
Length: 3, dtype: str

Internet Service
<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

Online Security
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

Online Backup
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

Device Protection
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Tech Support
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Streaming TV
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Streaming Movies
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Contract
<ArrowStringArray>
['Month-to-month', 'Two year', 'One year']
Length: 3, dtype: str

Paperless Billing
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Payment Method
<ArrowStringArray>
[             'Mailed check',          'Electronic check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

Total Charges
[108.15 151.65 820.5 ... 7362.9 346.45 6844.5]

Churn Label
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Churn Reason
<ArrowStringArray>
[             'Competitor made better offer',
                                     'Moved',
             'Competitor had better devices',
 'Competitor offered higher download speeds',
              'Competitor offered more data',
                            'Price too high',
                   'Product dissatisfaction',
                   'Service dissatisfaction',
           'Lack of self-service on Website',
                       'Network reliability',
                 'Limited range of services',
  'Lack of affordable download/upload speed',
                     'Long distance charges',
                        'Extra data charges',
                                'Don't know',
          'Poor expertise of online support',
           'Poor expertise of phone support',
              'Attitude of service provider',
                'Attitude of support person',
                                  'Deceased',
                                         nan]
Length: 21, dtype: str

In [14]:
# Checking how many customers stayed and how many churned
df["Churn Value"].value_counts()

Churn Value
0    5174
1    1869
Name: count, dtype: int64

In [15]:
# Inspection result 
# Around 73% of customers stayed and the rest churned
df["Churn Value"].value_counts(normalize=True) * 100

Churn Value
0    73.463013
1    26.536987
Name: proportion, dtype: float64

In [16]:
# Inspecting Total Charges
df["Total Charges"].unique()

array([108.15, 151.65, 820.5, ..., 7362.9, 346.45, 6844.5],
      shape=(6531,), dtype=object)

In [17]:
df[df["Total Charges"].astype(str).str.strip() == ""]
# There are 11 rows with blank Total Charges

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,,No,0,65,5188,NaN

## 9. Numerical Feature Inspection

For numerical features, I will look at their basic statistics to understand their ranges, central tendencies, and possible unusual values.

In [18]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000